In [1]:
import main
from Ball import Ball2D
from World import World
from PowerBar import PowerBar
from Text import Text
from Agent import Agent
import pygame

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
agent = Agent(150,45,900)
def main():

   
    pygame.init()

    clock = pygame.time.Clock()

    
    win_width = 1280
    win_height = 640

    screen = pygame.display.set_mode((win_width, win_height))
    pygame.display.set_caption('Basketball')

    world = World()
    power = PowerBar()
    scoreboard = Text()
    
    
    
    world.add_rim('disk-red.png', 5).set_pos([1000, 300])
    world.add_rim('disk-red.png', 5).set_pos([1075, 300])
    world.shot_from = 100
    dt = 0.1
    while(True):
        clock.tick(60)
        screen.fill(WHITE)
        #power.draw(screen)
        world.draw(screen)
        pygame.draw.arc(screen, RED, (50,50,50,50), 1, 1, 10)
        pygame.draw.line(screen, RED, [1000, 340], [1075, 340], 10)
       
        pygame.draw.line(screen, RED, [1075, 250], [1075, 640], 10)
        scoreboard.score_display(world, screen)
        
        if not world.shot:
            world.start(power, agent)
        else:
            won = world.update(dt, power, agent)  ### change position here
            

        pygame.display.update()

if __name__ == '__main__':
    main()

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
ShotFrom:
100
NPSUM: 0, Power R: 150, Angle R: 45
ShotFrom:
100
NPSUM: 0, Power R: 150, Angle R: 45
ShotFrom:
100
NPSUM: 0, Power R: 150, Angle R: 45
ShotFrom:
100
NPSUM: 0, Power R: 150, Angle R: 45
ShotFrom:
100
NPSUM: 0, Power R: 150, Angle R: 45
ShotFrom:
100
NPSUM: 0, Power R: 150, Angle R: 45
[100  37  25]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[100  26 109]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[100  16  84]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[100  10  60]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[100  14 105]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[100  43  25]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[  0   6 105]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 18 81]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 24 86]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 36 68]
NPSUM: 0, Power R: 150, Angle R: 4

[ 0 32 44]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  43 119]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  9 25]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 36 30]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  14 148]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[0 1 9]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  5 27]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  9 95]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  13 139]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 25 42]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  34 146]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  23 143]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  25 123]
NPSUM: 128, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  8 38]
NPSUM: 128, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  1 45]
NPSUM: 128, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 30 37]
NPSUM: 128, Power R: 150, Angle R: 45
WorldSHOT:100
[

[ 0 39 69]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  1 87]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 26 24]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 24 90]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 30 35]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 12 21]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 42 12]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  30 117]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  41 137]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 20 45]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 27 13]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  19 137]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  36 127]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 34 56]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 13 21]
NPSUM: 384, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 36 69]
NPSUM: 384, Power R: 150, Angle 

[  0   5 145]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  38 129]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  21 106]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 125]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 145]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  44 106]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 19 35]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 24  3]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 20 54]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 32 17]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  26 123]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[  0   3 119]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 15 95]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 125]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  37 119]
NPSUM: 1024, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  0 39]

[  0  10 116]
NPSUM: 1792, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  33 127]
NPSUM: 1792, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 35 25]
NPSUM: 1792, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  25 125]
NPSUM: 1792, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  7 61]
NPSUM: 1792, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 39 44]
NPSUM: 1792, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  2 88]
NPSUM: 1792, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  34 126]
NPSUM: 1920, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 25 40]
NPSUM: 1920, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  40 142]
NPSUM: 1920, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  1 67]
NPSUM: 1920, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  36 127]
NPSUM: 1920, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 13 37]
NPSUM: 1920, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 31 87]
NPSUM: 1920, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  8 80]
NPSUM: 1920, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  36 126]
NPSUM: 1

[  0  35 125]
NPSUM: 3584, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  25 134]
NPSUM: 3584, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  33 128]
NPSUM: 3584, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  19 117]
NPSUM: 3584, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 127]
NPSUM: 3712, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  44 147]
NPSUM: 3712, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 17 34]
NPSUM: 3712, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 128]
NPSUM: 3840, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 11 36]
NPSUM: 3840, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  34 125]
NPSUM: 3968, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 129]
NPSUM: 4096, Power R: 150, Angle R: 45
WorldSHOT:100
[0 0 0]
NPSUM: 4096, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 30 59]
NPSUM: 4096, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  3 24]
NPSUM: 4096, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  36 130]
NPSUM: 4224, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 127]

[ 0 41 77]
NPSUM: 8960, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 34 62]
NPSUM: 8960, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 127]
NPSUM: 9088, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  24 125]
NPSUM: 9216, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 124]
NPSUM: 9216, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 24 75]
NPSUM: 9216, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  27 105]
NPSUM: 9216, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  36 128]
NPSUM: 9216, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 44 20]
NPSUM: 9216, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 128]
NPSUM: 9344, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  39 146]
NPSUM: 9472, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  38 146]
NPSUM: 9472, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  32 121]
NPSUM: 9600, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  36 127]
NPSUM: 9600, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  38 147]
NPSUM: 9600, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 17 

[  0  33 125]
NPSUM: 14326, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  33 125]
NPSUM: 14454, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 16 58]
NPSUM: 14454, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  34 127]
NPSUM: 14582, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 128]
NPSUM: 14710, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  33 126]
NPSUM: 14710, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 16 58]
NPSUM: 14710, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 126]
NPSUM: 14838, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  2 81]
NPSUM: 14838, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  33 123]
NPSUM: 14966, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  33 122]
NPSUM: 15094, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  34 126]
NPSUM: 15222, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  25 123]
NPSUM: 15350, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 131]
NPSUM: 15350, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  36 126]
NPSUM: 15350, Power R: 150, Angle R: 45
Wor

[  0   9 111]
NPSUM: 20726, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  7 15]
NPSUM: 20726, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  34 128]
NPSUM: 20726, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  9 17]
NPSUM: 20726, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  34 125]
NPSUM: 20854, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  33 127]
NPSUM: 20854, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  34 129]
NPSUM: 20854, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 126]
NPSUM: 20982, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  25 124]
NPSUM: 20982, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  34 127]
NPSUM: 21110, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  35 128]
NPSUM: 21238, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0  3 22]
NPSUM: 21238, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 29 57]
NPSUM: 21238, Power R: 150, Angle R: 45
WorldSHOT:100
[ 0 13  0]
NPSUM: 21238, Power R: 150, Angle R: 45
WorldSHOT:100
[  0  32 123]
NPSUM: 21366, Power R: 150, Angle R: 45
WorldSHOT

[ 1 12 33]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 28 69]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:101
[1 0 0]
NPSUM: 0, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  36 132]
NPSUM: 128, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  28 136]
NPSUM: 128, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 12 63]
NPSUM: 128, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 43 86]
NPSUM: 128, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 22  7]
NPSUM: 128, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  33 125]
NPSUM: 256, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  27 125]
NPSUM: 256, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 15 65]
NPSUM: 256, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  38 126]
NPSUM: 256, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1  1 36]
NPSUM: 256, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1  1 15]
NPSUM: 256, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  10 102]
NPSUM: 256, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 24 50]
NPSUM: 256, Power R: 150, Angle R: 

[ 1 31 85]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 14 10]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 29 62]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1  1 57]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 21 75]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 17 62]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  25 143]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 14 80]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 10 79]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  36 134]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  37 139]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 17 64]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 40 38]
NPSUM: 640, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  34 124]
NPSUM: 768, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 41 31]
NPSUM: 768, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1  6 56]
NPSUM: 768, Power R: 150, Angle 

[ 1 34 10]
NPSUM: 2304, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 40 64]
NPSUM: 2304, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  34 122]
NPSUM: 2304, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 18 44]
NPSUM: 2304, Power R: 150, Angle R: 45
WorldSHOT:101
[1 0 0]
NPSUM: 2304, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 33 12]
NPSUM: 2304, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  33 125]
NPSUM: 2432, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 27 26]
NPSUM: 2432, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  29 118]
NPSUM: 2432, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 33 24]
NPSUM: 2432, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 24 97]
NPSUM: 2432, Power R: 150, Angle R: 45
WorldSHOT:101
[  1  11 143]
NPSUM: 2432, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1  1 61]
NPSUM: 2432, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 16 81]
NPSUM: 2432, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 35 29]
NPSUM: 2432, Power R: 150, Angle R: 45
WorldSHOT:101
[ 1 10  3]
NPSUM: 2432, Power R

SystemExit: 0

C:\Users\Anormal\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [3]:
s = ""
import numpy as np
np.savetxt("100.txt",agent.matrix[0],fmt='%-7.2f')

In [ ]:
f = open()